### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by Akm0d** [jordan9001/SpectrumDraw#1]
Include a Make file so It's easy to know how to compile everything

**Comment by jordan9001** [comment]
Qt projects create their own makefile depending on the system. You just call `qmake SpectroDraw.pro` which will create a MakeFile. With that makefile you can call make. Make sure you are using qmake with version 5 or greater.
I will put some instructions in the README later.
Here is more info.
[http://doc.qt.io/qt-4.8/qmake-running.html](http://doc.qt.io/qt-4.8/qmake-running.html)
